version: '3.4'

services:

  identity.data:
    container_name: identity.data
    environment:
      - SA_PASSWORD=P@ssword1
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - identity_data:/var/opt/mssql

  identity.api:
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=identity.data;Database=IdentityDb;User Id=sa;Password=P@ssword1
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "8001:80"

  microfrontend.api:
    container_name: microfrontend.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrlExternal=http://${SHELL_EXTERNAL_DNS_NAME_OR_IP}:8001
      - ConnectionString=mongodb://microfrontend.data:27017
      - IdentityUrl=http://identity.api
      - IdentityAudience=mfapiresource
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "8002:80"
  
  microfrontend.data:
    container_name: microfrontend.data
    ports:
      - "27017:27017"
    volumes:
      - microfrontend_data:/data/db 

  shell.app:
    container_name: shell.app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8003:80" 

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data


  