version: '3.4'

services:

  identity.data:
    image: mcr.microsoft.com/mssql/server:2019-latest

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
      - identity.data 

  shell.api:
    image: ${DOCKER_REGISTRY-}shellapi
    build:
      context: .
      dockerfile: Services/Shell/Shell.API/Dockerfile
    depends_on:
      - shell.data

  shell.data:
    image: mongo

  shell.app:
    image: ${DOCKER_REGISTRY-}shellapp
    build:
      context: .
      dockerfile: WebApps/ShellApp/Dockerfile
    depends_on:
      - shell.api
      - elasticsearch

  portainer:
    image: portainer/portainer-ce

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

volumes:
  identity_data:
  portainer_data:
  shell_data:
  elasticsearch-data:

