version: '3.4'

services:

  identity.data:
    container_name: identity.data
    environment:
      - SA_PASSWORD=P@ssword1
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - identity_data:/var/opt/mssql

  identity.api:
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=identity.data;Database=IdentityDb;User Id=sa;Password=P@ssword1
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "8001:80"

  shell.api:
    container_name: shell.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrlExternal=http://${SHELL_EXTERNAL_DNS_NAME_OR_IP}:8001
      - MongoDbSettings__ConnectionString=mongodb://shell.data:27017
      - MongoDbSettings__DbName=shell
      - IdentityUrl=http://identity.api
      - IdentityAudience=shellappresource
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "8002:80"

  shell.data:
    container_name: shell.data
    ports:
      - "27017:27017"
    volumes:
      - shell_data:/data/db 

  shell.app:
    container_name: shell.app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://${SHELL_EXTERNAL_DNS_NAME_OR_IP}:8001
      - CallBackUrl=http://${SHELL_EXTERNAL_DNS_NAME_OR_IP}:8003
      - Scope=shellappscope
      - PageServiceUrl=http://${SHELL_EXTERNAL_DNS_NAME_OR_IP}:8002
    ports:
      - "8003:80"
    depends_on:
      - identity.api

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  
  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

