version: '3.4'

services:

  identity.data:
    image: mcr.microsoft.com/mssql/server:2019-latest

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
      - identity.data 

  microfrontend.api:
    image: ${DOCKER_REGISTRY-}microfrontendapi
    build:
      context: .
      dockerfile: Services/MicroFrontend/MicroFrontend.API/Dockerfile
    depends_on:
      - microfrontend.data

  microfrontend.data:
    image: mongo

  shell.app:
    image: ${DOCKER_REGISTRY-}shellapp
    build:
      context: .
      dockerfile: WebApps/ShellApp/Dockerfile
    depends_on:
      - microfrontend.api

  portainer:
    image: portainer/portainer-ce

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

volumes:
  identity_data:
  portainer_data:
  microfrontend_data:
  elasticsearch-data:
